services:
  roulette:
    build: .             # Nutze das Dockerfile im aktuellen Ordner
    container_name: game # Entspricht --name
    stdin_open: true     # Entspricht -i (interactive)
    tty: true            # Entspricht -t (terminal)
    volumes:
      - .:/app           # Entspricht -v $(pwd):/app
    develop:
      watch:
        - action: sync
          path: ./game.py
          target: /app/game.py